##
## This file is automatically generated.  DO NOT EDIT.
##
plugin_modules = [
    'plugin_CSV',
    'plugin_HTML',
    'plugin_RichReader',
    'plugin_TaggedText',
    'plugin_TealDoc',
    'plugin_Text',
    'plugin_URLStream',
    'plugin_basicdoc',
    'plugin_copydoc',
    'plugin_dbfieldguess',
    'plugin_docoutput',
    'plugin_frotz',
    'plugin_instjpilot',
    'plugin_instpisock',
    'plugin_jfile',
    'plugin_pdbinput',
    'plugin_pdboutput',
    'plugin_textoutput',
    'plugin_ztxtoutput'
    ]
